source 'https://github.com/CocoaPods/Specs.git' 
source 'http://gitlab.jiehun.tech/App/iOS/Modularization/HBHSpecs.git'

platform :ios, '9.0'
use_frameworks!

target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HBHBaseLib' 	# 基础扩展库

  # Pods for SwiftProject

end
