# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TFPopup' # 通用弹出框架

  # Pods for Demo-Project

end
